// Generated by tools/build-sw.mjs — do not edit by hand.
const VERSION = 'a493b8a20af0';
const CACHE = 'ej14-' + VERSION;
const FONTS = 'ej14-fonts';
const PRECACHE = ["ch/",
  "css/tags.css",
  "data/adverbs.json",
  "data/ch01.json",
  "data/ch02.json",
  "data/ch03.json",
  "data/ch04.json",
  "data/ch05.json",
  "data/ch06.json",
  "data/ch07.json",
  "data/ch08.json",
  "data/ch09.json",
  "data/ch10.json",
  "data/confusions.json",
  "data/grammar.json",
  "data/lessons.json",
  "data/particles.json",
  "data/phrases.json",
  "data/scenes.json",
  "data/tr/adverbs.json",
  "data/tr/confusions.json",
  "data/tr/ex.json",
  "data/tr/gloss.json",
  "data/tr/grammar.json",
  "data/tr/lessons.json",
  "data/tr/particles.json",
  "data/tr/phrases.json",
  "data/tr/scenes.json",
  "data/tr/verbs.json",
  "data/verbs.json",
  "data/vocab.json",
  "drill/",
  "favicon.ico",
  "grammar/",
  "icons/apple-touch-icon.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon.svg",
  "./",
  "js/app.js",
  "js/chunks.js",
  "js/exparse.js",
  "js/flash.js",
  "js/game.js",
  "js/i18n.js",
  "js/quiz.js",
  "js/romaji.js",
  "js/scope.js",
  "js/speech.js",
  "js/srs.js",
  "lesson/",
  "manifest.webmanifest",
  "print/",
  "progress/",
  "scenes/",
  "test/",
  "tr/ch/",
  "tr/drill/",
  "tr/grammar/",
  "tr/",
  "tr/lesson/",
  "tr/manifest.webmanifest",
  "tr/print/",
  "tr/progress/",
  "tr/scenes/",
  "tr/test/",
  "tr/words/",
  "words/"];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE.map(u => new Request(u, { cache: 'reload' })))).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k.startsWith('ej14-') && k !== CACHE && k !== FONTS).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  // Google Fonts: serve from cache, refresh in the background.
  if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') {
    e.respondWith(caches.open(FONTS).then(async c => {
      const hit = await c.match(req);
      const net = fetch(req).then(r => { if (r.ok || r.type === 'opaque') c.put(req, r.clone()); return r; }).catch(() => hit);
      return hit || net;
    }));
    return;
  }
  if (url.origin !== location.origin) return;

  // Pages: network first so content stays fresh online; cached copy (ignoring ?day= etc.) offline.
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).then(r => {
      if (r.ok) { const copy = r.clone(); caches.open(CACHE).then(c => c.put(url.pathname, copy)); }
      return r;
    }).catch(async () => (await caches.match(url.pathname, { ignoreSearch: true }))
      || (await caches.match(req, { ignoreSearch: true }))
      || caches.match(url.pathname.startsWith(new URL('tr/', self.registration.scope).pathname) ? 'tr/' : './')));
    return;
  }

  // Scripts, styles, data, icons: cache first (the cache is versioned), network as fallback.
  e.respondWith(caches.match(req).then(hit => hit || fetch(req).then(r => {
    if (r.ok) { const copy = r.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
    return r;
  })));
});
