#!/usr/bin/env node
// Writes sw.js: the service worker that makes the site an installable, offline-capable app.
//   node tools/build-sw.mjs
// Run it last, after any change to pages, js, css or data — the cache version is a hash of every
// precached file, so returning users get the new files on their next visit.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const walk = dir => fs.readdirSync(path.join(ROOT, dir), { withFileTypes: true }).flatMap(d => {
  const rel = dir ? `${dir}/${d.name}` : d.name;
  return d.isDirectory() ? walk(rel) : [rel];
});

// App pages (not the printable worksheets), plus everything they load.
const PAGES = ['', 'lesson/', 'grammar/', 'words/', 'scenes/', 'ch/', 'drill/', 'test/', 'progress/', 'print/'];
const files = [
  ...PAGES.flatMap(p => [`${p}index.html`, `tr/${p}index.html`, `fr/${p}index.html`]),
  'manifest.webmanifest', 'tr/manifest.webmanifest', 'fr/manifest.webmanifest', 'favicon.ico',
  ...walk('css'), ...walk('js'), ...walk('data'), ...walk('icons'),
].filter(f => /\.(html|css|js|json|webmanifest|png|svg|ico)$/.test(f) && !/-[abc]\.json$/.test(f)).sort();

const hash = crypto.createHash('sha256');
for (const f of files) hash.update(f).update(fs.readFileSync(path.join(ROOT, f)));
const VERSION = hash.digest('hex').slice(0, 12);
// Pages are cached under their directory URL ("lesson/"), which is how they are linked.
const urls = files.map(f => f.replace(/(^|\/)index\.html$/, '$1') || './');

const sw = `// Generated by tools/build-sw.mjs — do not edit by hand.
const VERSION = '${VERSION}';
const CACHE = 'ej14-' + VERSION;
const FONTS = 'ej14-fonts';
const PRECACHE = ${JSON.stringify(urls, null, 0).replace(/","/g, '",\n  "')};

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE.map(u => new Request(u, { cache: 'reload' })))).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k.startsWith('ej14-') && k !== CACHE && k !== FONTS).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  // Google Fonts: serve from cache, refresh in the background.
  if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') {
    e.respondWith(caches.open(FONTS).then(async c => {
      const hit = await c.match(req);
      const net = fetch(req).then(r => { if (r.ok || r.type === 'opaque') c.put(req, r.clone()); return r; }).catch(() => hit);
      return hit || net;
    }));
    return;
  }
  if (url.origin !== location.origin) return;

  // Pages: network first so content stays fresh online; cached copy (ignoring ?day= etc.) offline.
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).then(r => {
      if (r.ok) { const copy = r.clone(); caches.open(CACHE).then(c => c.put(url.pathname, copy)); }
      return r;
    }).catch(async () => (await caches.match(url.pathname, { ignoreSearch: true }))
      || (await caches.match(req, { ignoreSearch: true }))
      || caches.match(['tr', 'fr'].find(c => url.pathname.startsWith(new URL(c + '/', self.registration.scope).pathname)) ? url.pathname.replace(/^.*?\/(tr|fr)\/.*$/, '$1/') : './')));
    return;
  }

  // Scripts, styles, data, icons: cache first (the cache is versioned), network as fallback.
  e.respondWith(caches.match(req).then(hit => hit || fetch(req).then(r => {
    if (r.ok) { const copy = r.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
    return r;
  })));
});
`;
fs.writeFileSync(path.join(ROOT, 'sw.js'), sw, 'utf8');
console.log(`sw.js: ${urls.length} files precached, version ${VERSION}.`);
